// lib/templateMarketplace/defaultTemplates.js — 16 safe default industry blueprint packs.
// No real phones/emails/payment refs/API keys. Everything dry-run + preview-only.
'use strict';
const now=()=>new Date().toISOString();
function tpl(o){
  return Object.assign({
    category:'industry_blueprint', audience:'business_owner', tags:[], modulesUsed:[],
    includedRecipes:[], includedPlaybooks:[], includedFlowNodes:[], includedCampaigns:[],
    includedSupportArticles:[], includedOwnerTasks:[], recommendedPlan:'pro', difficulty:'beginner',
    estimatedSetupTime:'15m', language:'roman_urdu', visibility:'reseller_safe', status:'active',
    dryRun:true, createdAt:now(), updatedAt:now(),
  }, o);
}
const T=[
  tpl({ id:'tpl_ai_tools_reseller', slug:'ai-tools-reseller-starter', title:'AI Tools Reseller Starter', industry:'AI Tools Reseller',
    description:'Sell ChatGPT/Claude/Midjourney plans on WhatsApp with order + payment follow-ups.', visibility:'public_safe',
    modulesUsed:['unifiedSetup','channelAutomation','customer360','kpiCommand'],
    includedRecipes:['rcp_new_lead_followup','rcp_new_order_owner_alert','rcp_payment_pending_reminder'],
    includedCampaigns:['Flash sale draft','New tool launch draft'], includedSupportArticles:['How to order','Refund policy (demo)'],
    includedOwnerTasks:['Review pending orders','Confirm stock'], tags:['ai','reseller','whatsapp'] }),
  tpl({ id:'tpl_ecommerce_growth', slug:'ecommerce-growth-starter', title:'Ecommerce Growth Starter', industry:'Ecommerce Store',
    description:'Catalog, stock alerts, abandoned-order follow-ups and flash sale drafts.', visibility:'public_safe',
    modulesUsed:['storeBuilder','channelAutomation','growthCampaign','kpiCommand'],
    includedRecipes:['rcp_new_order_owner_alert','rcp_price_drop_campaign'], tags:['ecommerce','catalog'] }),
  tpl({ id:'tpl_wa_channel_publisher', slug:'whatsapp-channel-publisher', title:'WhatsApp Channel Publisher', industry:'WhatsApp Channel Growth',
    description:'Plan and approve channel posts with a safe approval queue (no live sending).',
    modulesUsed:['channelAutomation','complianceCenter'], includedRecipes:['rcp_channel_post_approval'], tags:['channel','content'] }),
  tpl({ id:'tpl_support_inbox', slug:'customer-support-inbox', title:'Customer Support Inbox', industry:'Customer Support',
    description:'Triage tickets, suggest KB articles and draft replies for review.',
    modulesUsed:['customer360','supportHelpdesk'], includedRecipes:['rcp_ticket_resolved_kb'], tags:['support','helpdesk'] }),
  tpl({ id:'tpl_voice_ai_support', slug:'voice-ai-support-assistant', title:'Voice AI Support Assistant', industry:'Voice AI Support',
    description:'Turn voice transcripts into tickets and reply drafts (no live calls).',
    modulesUsed:['voiceAI','supportHelpdesk'], includedRecipes:['rcp_voice_transcript_ticket'], tags:['voice','support'] }),
  tpl({ id:'tpl_marketplace_intel', slug:'marketplace-seller-buyer', title:'Marketplace Seller/Buyer Intelligence', industry:'Marketplace',
    description:'Match seller offers with buyer requests and watch SKU price changes.',
    modulesUsed:['marketplaceIntelligence','kpiCommand'], includedRecipes:['rcp_price_drop_campaign'], tags:['marketplace','b2b'] }),
  tpl({ id:'tpl_restaurant_followup', slug:'restaurant-order-followup', title:'Restaurant Order Follow-up', industry:'Restaurant',
    description:'Take demo orders, send prep updates and request feedback drafts.',
    modulesUsed:['channelAutomation','customer360'], includedRecipes:['rcp_new_order_owner_alert'], tags:['restaurant','food'] }),
  tpl({ id:'tpl_real_estate_leads', slug:'real-estate-lead-followup', title:'Real Estate Lead Follow-up', industry:'Real Estate',
    description:'Capture property leads, schedule viewings and nurture follow-up drafts.',
    modulesUsed:['customer360','growthCampaign'], includedRecipes:['rcp_new_lead_followup'], tags:['realestate','leads'] }),
  tpl({ id:'tpl_education_channel', slug:'education-scholarship-channel', title:'Education/Scholarship Channel', industry:'Education',
    description:'Publish scholarship/course alerts and answer FAQs with drafts.',
    modulesUsed:['channelAutomation','supportHelpdesk'], includedRecipes:['rcp_channel_post_approval'], tags:['education','scholarship'] }),
  tpl({ id:'tpl_jobs_channel', slug:'jobs-channel-automation', title:'Jobs Channel Automation', industry:'Jobs Channel',
    description:'Curate job posts, dedupe listings and schedule post drafts.',
    modulesUsed:['channelAutomation'], includedRecipes:['rcp_channel_post_approval'], tags:['jobs','channel'] }),
  tpl({ id:'tpl_digital_agency', slug:'digital-agency-onboarding', title:'Digital Agency Client Onboarding', industry:'Digital Agency',
    description:'Onboard clients with checklists, kickoff tasks and status drafts.', recommendedPlan:'business',
    modulesUsed:['unifiedSetup','ownerCommand'], includedRecipes:['rcp_trial_onboarding'], tags:['agency','onboarding'] }),
  tpl({ id:'tpl_wholesale_dealer', slug:'wholesale-dealer-rates-stock', title:'Wholesale Dealer Rates/Stock', industry:'Wholesale Dealer',
    description:'Broadcast rate sheets and stock updates with approval drafts.',
    modulesUsed:['channelAutomation','storeBuilder'], includedRecipes:['rcp_price_drop_campaign'], tags:['wholesale','rates'] }),
  tpl({ id:'tpl_local_shop_crm', slug:'local-shop-crm', title:'Local Shop CRM', industry:'Local Shop',
    description:'Lightweight CRM for repeat buyers with reminder drafts.',
    modulesUsed:['customer360'], includedRecipes:['rcp_new_lead_followup'], tags:['retail','crm'], difficulty:'beginner' }),
  tpl({ id:'tpl_public_saas_funnel', slug:'public-saas-funnel-launch', title:'Public SaaS Funnel Launch', industry:'Public SaaS Funnel',
    description:'Landing + pricing + lead capture preview wiring (no live signups).', visibility:'public_safe',
    modulesUsed:['publicSaasFunnel','saasBilling'], includedRecipes:['rcp_trial_onboarding'], tags:['saas','funnel'] }),
  tpl({ id:'tpl_reseller_partner', slug:'reseller-partner-onboarding', title:'Reseller Partner Onboarding', industry:'Reseller Partner',
    description:'Onboard partners with asset packs and commission preview.', visibility:'reseller_safe', category:'reseller_asset',
    modulesUsed:['resellerPortal'], includedRecipes:['rcp_reseller_referral'], tags:['reseller','partner'] }),
  tpl({ id:'tpl_pilot_customer', slug:'pilot-trial-customer-success', title:'Pilot Trial Customer Success', industry:'Pilot Customer',
    description:'Track pilot health, escalate risks and nurture success drafts.',
    modulesUsed:['ownerCommand','supportHelpdesk'], includedRecipes:['rcp_pilot_high_risk'], tags:['pilot','success'] }),
];
module.exports={ DEFAULT_TEMPLATES:T };
