 'use strict';
 /**
  * mergeRiskScanner.js — flags files likely to conflict when Gumloop later pulls
     * GitHub main and merges this handoff in. Pure analysis over a supplied file map.
     */
 const RISKY = [
   { file: 'server.js', riskLevel: 'high', reason: 'Shared entry; route mounts appended via hook block.',
 recommendedMergeAction: 'append hook only', safePatchNotes: 'Keep BEGIN/END GUMLOOP HANDOFF HOOK; do not overwrite existing app.use mounts. Run node --check after merge.' },
   { file: 'public/index.html', riskLevel: 'high', reason: 'Shared nav; dashboard link appended via hook block.',
 recommendedMergeAction: 'verify dashboard link', safePatchNotes: 'Add single nav link inside existing nav; preserve remote markup.' },
   { file: 'package.json', riskLevel: 'medium', reason: 'scripts block edited by multiple layers.',
 recommendedMergeAction: 'do not overwrite', safePatchNotes: 'Merge only the two gumloop-handoff:* script lines; keep existing scripts.' },
   { file: 'package-lock.json', riskLevel: 'medium', reason: 'Regenerated by npm install; frequent conflicts.',
 recommendedMergeAction: 'preserve existing remote changes', safePatchNotes: 'Prefer remote lockfile; re-run npm install locally. Do not hand-merge.' },
   { file: '.env.example', riskLevel: 'low', reason: 'Append-only placeholders.', recommendedMergeAction: 'append hook only', safePatchNotes: 'Add GUMLOOP_HANDOFF_* keys if missing; never add real secrets.' },
   { file: '.gitignore', riskLevel: 'low', reason: 'Append-only protections.', recommendedMergeAction: 'append hook only',
 safePatchNotes: 'Union of ignore entries; never remove existing.' },
   { file: 'README.md', riskLevel: 'low', reason: 'Docs index may diverge.', recommendedMergeAction: 'manual review required', safePatchNotes: 'Merge section additions; resolve prose by hand.' },
 ];

 function scan(fileMap) {
      fileMap = fileMap || {};
      const risks = RISKY.map((r) => {
        const present = Object.prototype.hasOwnProperty.call(fileMap, r.file);
        return Object.assign({}, r, { present, status: present ? 'review_on_merge' : 'skip_if_duplicate' });
      });
      return {
        generatedAt: new Date().toISOString(),
        dryRun: true,
        totalRisky: risks.filter((r) => r.present).length,
        risks,
      };
 }

 module.exports = { scan, RISKY };
