'use strict';
const store = require('./store');
const ruleModel = require('./anomalyRuleModel');
const alertModel = require('./alertModel');
const evaluator = require('./ruleEvaluator');
const signals = require('./moduleSignalAdapter');
const recommend = require('./actionRecommendation');
function activeRules() { const r = store.readRules(); return r.length ? r : ruleModel.defaults(); }
function detect() { const collected = signals.collect(); const metrics = collected.metrics || {}; const preAlerts = collected.preAlerts || []; const warnings = collected.warnings || []; const detected = []; for (const rule of activeRules()) { if (rule.enabled === false) continue; const value = metrics[rule.metricKey]; if (value === undefined) continue; const r = evaluator.evaluate(rule, value); if (!r.matched) continue; detected.push(alertModel.build({ title: rule.name.replace(/_/g, ' '), category: rule.category, severity: rule.severity, sourceModule: rule.sourceModule, signalKey: rule.metricKey, summary: `${rule.metricKey} = ${r.detectedValue} (threshold ${rule.condition} ${r.threshold})`, detectedValue: r.detectedValue, threshold: r.threshold, recommendedAction: recommend.forRule ? recommend.forRule(rule) : 'review this metric' })); } for (const pa of preAlerts) detected.push(alertModel.build({ title: pa.summary || 'Anomaly signal', category: pa.category || 'finance', severity: pa.severity || 'high', sourceModule: pa.sourceModule || 'anomaly', signalKey: pa.signalKey || 'anomaly', summary: pa.summary || 'anomaly signal', detectedValue: pa.detectedValue, recommendedAction: 'investigate anomaly source' })); const existing = store.readAlerts(); const openKeys = new Set(existing.filter((a) => !['resolved_preview','dismissed_preview'].includes(a.status)).map((a) => `${a.sourceModule}:${a.signalKey}`)); const fresh = detected.filter((a) => !openKeys.has(`${a.sourceModule}:${a.signalKey}`)); store.writeAlerts(fresh.concat(existing).slice(0, 2000)); return { ok:true, dryRun:true, detectedPreview:fresh.length, scannedModules: collected.scannedModules || [], warnings, blockers:[], alerts:fresh }; }
function list() { return store.readAlerts(); }
module.exports = { activeRules, detect, list };
