'use strict';
const store = require('./store');
const model = require('./invoiceModel');
const calc = require('./taxDiscountCalculator');
const { redactDeep } = require('./redactor');
function applyTotals(inv, calcInput) { const c = calc.calculate({ items: inv.items, ...(calcInput || {}) }); inv.subtotalPreview = c.subtotalPreview; inv.discountPreview = c.discountPreview; inv.taxPreview = c.taxPreview; inv.shippingPreview = c.shippingPreview; inv.totalPreview = c.totalPreview; inv.balanceDuePreview = calc.round2(Math.max(0, c.totalPreview - (inv.paidAmountPreview || 0))); return inv; }
function create(input) { const invoices = store.readInvoices(); const inv = model.build(input, invoices.length); applyTotals(inv, input); if (inv.paidAmountPreview <= 0) inv.status = 'draft'; else if (inv.paidAmountPreview < inv.totalPreview) inv.status = 'partially_paid_preview'; else inv.status = 'paid_preview'; invoices.unshift(inv); if (invoices.length > 3000) invoices.length = 3000; store.writeInvoices(invoices); return redactDeep(inv); }
function list(filter) { let items = store.readInvoices(); const f = filter || {}; if (f.status) items = items.filter((x) => x.status === f.status); if (f.source) items = items.filter((x) => x.sourceModule === f.source); if (f.q) { const q = String(f.q).toLowerCase(); items = items.filter((x) => (x.customerNameSafe || '').toLowerCase().includes(q) || (x.invoiceNumber || '').toLowerCase().includes(q)); } return items.slice(0, Number.isFinite(f.limit) ? f.limit : 100).map(redactDeep); }
function getRaw(id) { return store.readInvoices().find((x) => x.id === id || x.invoiceNumber === id) || null; }
function get(id) { const x = getRaw(id); return x ? redactDeep(x) : null; }
function update(id, patch) { const items = store.readInvoices(); const idx = items.findIndex((x) => x.id === id || x.invoiceNumber === id); if (idx === -1) return null; const inv = items[idx]; const b = patch || {}; if (Array.isArray(b.items)) inv.items = model.normalizeItems(b.items); if (b.dueDate !== undefined) inv.dueDate = b.dueDate; if (model.INVOICE_STATUSES.includes(b.status)) inv.status = b.status; if (b.paidAmount !== undefined) inv.paidAmountPreview = Math.max(0, Number(b.paidAmount) || 0); applyTotals(inv, b); inv.dryRun = true; inv.updatedAt = new Date().toISOString(); items[idx] = inv; store.writeInvoices(items); return redactDeep(inv); }
function sendPreview(id) { const items = store.readInvoices(); const idx = items.findIndex((x) => x.id === id || x.invoiceNumber === id); if (idx === -1) return null; if (items[idx].status === 'draft') items[idx].status = 'sent_preview'; items[idx].updatedAt = new Date().toISOString(); store.writeInvoices(items); return { ok:true, dryRun:true, liveSend:false, invoiceId:items[idx].id, status:items[idx].status, note:'preview only; nothing sent' }; }
function paymentPreview(id, amount) { const items = store.readInvoices(); const idx = items.findIndex((x) => x.id === id || x.invoiceNumber === id); if (idx === -1) return null; const inv = items[idx]; const add = Math.max(0, Number(amount) || 0); const newPaid = calc.round2((inv.paidAmountPreview || 0) + add); const balance = calc.round2(Math.max(0, inv.totalPreview - newPaid)); inv.paidAmountPreview = newPaid; inv.balanceDuePreview = balance; inv.status = newPaid <= 0 ? 'draft' : (balance > 0 ? 'partially_paid_preview' : 'paid_preview'); inv.updatedAt = new Date().toISOString(); items[idx] = inv; store.writeInvoices(items); return { ok:true, dryRun:true, liveActionsEnabled:false, invoiceId:inv.id, paidAmountPreview:newPaid, balanceDuePreview:balance, status:inv.status, warnings:[], blockers:[] }; }
module.exports = { create, list, get, getRaw, update, sendPreview, paymentPreview, applyTotals };
