// lib/insightsDigest/adapters.js — fault-tolerant read-only adapters over every module.
function safe(fn) { try { const v = fn(); return v == null ? { available: false } : { available: true, ...v }; } catch (e) { return { available: false, error: e.message }; } }
function analytics(storeId) { return safe(() => { const a = require('../analyticsInsights'); const snap = a.buildStoreSnapshot(storeId); return { revenue: snap.headline.revenue, mrr: snap.headline.mrr, customers: snap.headline.customers, orders: snap.headline.orders, leadToCustomerPct: snap.headline.leadToCustomerPct, wowGrowthPct: snap.revenue ? snap.revenue.wowGrowthPct : null, topChannel: (snap.channels && snap.channels[0]) ? snap.channels[0].channel : null }; }); }
function churn(storeId) { return safe(() => { const cm = require('../analyticsInsights/churnModel'); const storeCRM = require('../storeCRM'); const scores = cm.buildScores(storeCRM.getAllCustomers(storeId) || []); return { predictedChurnRatePct: scores.predictedChurnRatePct, revenueAtRisk: scores.revenueAtRisk, highRisk: scores.bands ? scores.bands.high : 0, saveListTop: (scores.saveList || []).slice(0, 3).map((s) => ({ name: s.name || s.phone, risk: s.churnRisk, atRisk: s.revenueAtRisk })) }; }); }
function reEngagement(storeId) { return safe(() => { const re = require('../reEngagement'); const c = re.plan(storeId, {}); return { targetedToday: c.summary.targeted, revenueAtRiskTargeted: c.summary.revenueAtRiskTargeted, mode: c.mode }; }); }
function experiments(storeId) { return safe(() => { const ex = require('../experiments'); const list = ex.listExperiments(storeId) || []; return { total: list.length, running: list.filter((e) => e.status === 'running').length, decided: list.filter((e) => e.status === 'decided').length }; }); }
function attribution(storeId) { return safe(() => { const at = require('../attribution'); const snap = at.buildSnapshot(storeId); const lt = snap.models.last_touch ? snap.models.last_touch.byChannel : []; const ft = snap.models.first_touch ? snap.models.first_touch.byChannel : []; return { conversions: snap.summary.conversions, multiTouchSharePct: snap.summary.multiTouchSharePct, topCloser: lt[0] ? lt[0].channel : null, topOpener: ft[0] ? ft[0].channel : null }; }); }
function cohorts(storeId) { return safe(() => { const co = require('../cohorts'); const snap = co.buildSnapshot(storeId); return { cohorts: snap.summary.cohorts, avgM1RetentionPct: snap.summary.avgM1RetentionPct, m1RetentionTrendPct: snap.summary.m1RetentionTrendPct }; }); }
function forecast(storeId) { return safe(() => { const fc = require('../forecasting'); const snap = fc.buildSnapshot(storeId, 30); return { next30Revenue: snap.summary.next30Revenue, next30Low: snap.summary.next30RevenueLow, next30High: snap.summary.next30RevenueHigh, projectedGrowthPct: snap.summary.projectedGrowthPct, backtestAccuracyPct: snap.summary.backtestAccuracyPct }; }); }
function alerts(storeId) { return safe(() => { const al = require('../anomalies'); const list = al.listAlerts(storeId, { includeAcknowledged: false }) || []; return { open: list.length, critical: list.filter((a) => a.severity === 'critical').length, warning: list.filter((a) => a.severity === 'warning').length, top: list.slice(0, 3).map((a) => ({ severity: a.severity, headline: a.headline })) }; }); }
function clv(storeId) { return safe(() => { const m = require('../clv'); const snap = m.buildSnapshot(storeId); return { predictedCLVTotal: snap.summary.predictedCLVTotal, avgPredictedCLV: snap.summary.avgPredictedCLV }; }); }
function concentration(storeId) { return safe(() => { const m = require('../concentration'); const snap = m.buildSnapshot(storeId); return { top5SharePct: snap.summary.top5SharePct, singleBuyerExposurePct: snap.summary.singleBuyerExposurePct, risk: snap.summary.risk }; }); }
function engagement(storeId) { return safe(() => { const m = require('../engagement'); const snap = m.buildSnapshot(storeId); return { replyRatePct: snap.summary.replyRatePct, medianReplyLatencyHours: snap.summary.medianReplyLatencyHours, messageToOrderPct: snap.summary.messageToOrderPct }; }); }
module.exports = { analytics, churn, reEngagement, experiments, attribution, cohorts, forecast, alerts, clv, concentration, engagement };
