// lib/voiceAI/index.js — Barrel export for the Voice AI Command Center.

module.exports = {
  config: require('./config').config,
  providerRegistry: require('./providerRegistry'),
  ttsEngine: require('./ttsEngine'),
  sttEngine: require('./sttEngine'),
  consentGuard: require('./consentGuard'),
  consentStore: require('./consentStore'),
  optInGuard: require('./optInGuard'),
  conversationManager: require('./conversationManager'),
  summaryBuilder: require('./summaryBuilder'),
  replyDraftBuilder: require('./replyDraftBuilder'),
  voiceAgentRouter: require('./voiceAgentRouter'),
  agentRegistry: require('./agentRegistry'),
  templates: require('./templates'),
  templateRenderer: require('./templateRenderer'),
  voiceQueue: require('./voiceQueue'),
  approvalWorkflow: require('./approvalWorkflow'),
  scheduler: require('./scheduler'),
  whatsappVoiceAdapter: require('./adapters/whatsappVoiceAdapter'),
  localWorkerVoiceAdapter: require('./adapters/localWorkerVoiceAdapter'),
  telegramVoiceAdapter: require('./adapters/telegramVoiceAdapter'),
  socialVoiceAdapter: require('./adapters/socialVoiceAdapter'),
  channelVoiceAdapter: require('./adapters/channelVoiceAdapter'),
  ecommerceVoice: require('./ecommerceVoice'),
  productVoiceover: require('./productVoiceover'),
  orderVoiceAssistant: require('./orderVoiceAssistant'),
  flowNodes: require('./flowNodes'),
  adminCommands: require('./adminCommands'),
  auditLog: require('./auditLog'),
  historyStore: require('./historyStore'),
  reportBuilder: require('./reportBuilder'),
  doctor: require('./doctor'),
  cleanup: require('./cleanup'),
  retry: require('./retry'),
  voiceProfiles: require('./voiceProfiles'),
};
