// lib/voiceAI/providerConfig.js — Static capability + env-key map for every supported
// voice provider. This file contains NO secrets, only the NAMES of env vars to look for.

module.exports = {
  mock_dry_run: {
    id: 'mock_dry_run', label: 'Mock (Dry-Run)',
    capabilities: ['text_to_speech', 'speech_to_text', 'voiceover_generation'],
    requiresApiKey: false, envKeys: [],
    supportsUrdu: true, supportsEnglish: true, supportsRomanUrdu: true,
    supportsVoiceClone: false, consentRequired: false, riskLevel: 'none',
    notes: 'Default safe provider. Never calls external services. Returns deterministic previews.',
  },
  elevenlabs: {
    id: 'elevenlabs', label: 'ElevenLabs',
    capabilities: ['text_to_speech', 'voiceover_generation', 'voice_clone_optional_consent_only'],
    requiresApiKey: true, envKeys: ['ELEVENLABS_API_KEY'],
    supportsUrdu: true, supportsEnglish: true, supportsRomanUrdu: true,
    supportsVoiceClone: true, consentRequired: true, riskLevel: 'medium',
    notes: 'High-quality TTS + optional voice cloning. Cloning disabled unless consent + env flag set.',
  },
  openai_audio: {
    id: 'openai_audio', label: 'OpenAI Audio',
    capabilities: ['text_to_speech', 'speech_to_text'],
    requiresApiKey: true, envKeys: ['OPENAI_AUDIO_API_KEY'],
    supportsUrdu: true, supportsEnglish: true, supportsRomanUrdu: true,
    supportsVoiceClone: false, consentRequired: true, riskLevel: 'low',
    notes: 'TTS + Whisper STT via OpenAI. No cloning.',
  },
  google_speech: {
    id: 'google_speech', label: 'Google Speech',
    capabilities: ['text_to_speech', 'speech_to_text', 'voice_translation'],
    requiresApiKey: true, envKeys: ['GOOGLE_SPEECH_API_KEY'],
    supportsUrdu: true, supportsEnglish: true, supportsRomanUrdu: false,
    supportsVoiceClone: false, consentRequired: true, riskLevel: 'low', notes: 'Google Cloud STT/TTS.',
  },
  azure_speech: {
    id: 'azure_speech', label: 'Azure Speech',
    capabilities: ['text_to_speech', 'speech_to_text'],
    requiresApiKey: true, envKeys: ['AZURE_SPEECH_KEY', 'AZURE_SPEECH_REGION'],
    supportsUrdu: true, supportsEnglish: true, supportsRomanUrdu: false,
    supportsVoiceClone: false, consentRequired: true, riskLevel: 'low', notes: 'Azure Cognitive Speech.',
  },
  aws_polly: {
    id: 'aws_polly', label: 'AWS Polly',
    capabilities: ['text_to_speech'],
    requiresApiKey: true, envKeys: ['AWS_POLLY_ACCESS_KEY_ID', 'AWS_POLLY_SECRET_ACCESS_KEY', 'AWS_POLLY_REGION'],
    supportsUrdu: false, supportsEnglish: true, supportsRomanUrdu: false,
    supportsVoiceClone: false, consentRequired: true, riskLevel: 'low', notes: 'AWS Polly TTS.',
  },
  deepgram: {
    id: 'deepgram', label: 'Deepgram',
    capabilities: ['speech_to_text'],
    requiresApiKey: true, envKeys: ['DEEPGRAM_API_KEY'],
    supportsUrdu: false, supportsEnglish: true, supportsRomanUrdu: false,
    supportsVoiceClone: false, consentRequired: true, riskLevel: 'low', notes: 'Deepgram STT.',
  },
  whisper_local: {
    id: 'whisper_local', label: 'Whisper (Local)',
    capabilities: ['speech_to_text'],
    requiresApiKey: false, envKeys: [],
    supportsUrdu: true, supportsEnglish: true, supportsRomanUrdu: true,
    supportsVoiceClone: false, consentRequired: false, riskLevel: 'none',
    notes: 'Local STT if a whisper binary/model is configured. No external upload.',
  },
  browser_speech: {
    id: 'browser_speech', label: 'Browser Speech API',
    capabilities: ['text_to_speech', 'speech_to_text'],
    requiresApiKey: false, envKeys: [],
    supportsUrdu: false, supportsEnglish: true, supportsRomanUrdu: true,
    supportsVoiceClone: false, consentRequired: false, riskLevel: 'none',
    notes: 'Client-side Web Speech API. Runs in the user browser only.',
  },
  manual_upload: {
    id: 'manual_upload', label: 'Manual Upload',
    capabilities: ['text_to_speech', 'speech_to_text', 'audio_cleanup'],
    requiresApiKey: false, envKeys: [],
    supportsUrdu: true, supportsEnglish: true, supportsRomanUrdu: true,
    supportsVoiceClone: false, consentRequired: false, riskLevel: 'none',
    notes: 'Operator manually records/uploads audio. No automation.',
  },
};
