// lib/reEngagement/engine.js — plan win-back batches from churn output (safety-railed, dry-run default).
const crypto = require('crypto');
const storeCRM = require('../storeCRM');
const { renderMergeFields } = require('../mergeFields');
const churnModel = require('../analyticsInsights/churnModel');
const { TEMPLATES, LOYALTY_PERK, pickTemplate } = require('./templates');
const ledger = require('./campaignStore');
const DAY = 86400000;
function cfg() { return { live: String(process.env.REENGAGE_LIVE || 'false').toLowerCase() === 'true', dailyCap: Number(process.env.REENGAGE_DAILY_CAP || 50), cooldownDays: Number(process.env.REENGAGE_COOLDOWN_DAYS || 14), minRisk: Number(process.env.REENGAGE_MIN_RISK || 40) }; }
function newId() { try { if (crypto.randomUUID) return 're_' + crypto.randomUUID().slice(0, 12); } catch {} return 're_' + crypto.randomBytes(8).toString('hex'); }
function candidates(storeId, now = Date.now()) { const customers = storeCRM.getAllCustomers(storeId) || []; if (!customers.length) return []; const scored = churnModel.buildScores(customers, now); return scored.topRisk.concat(scored.saveList).filter((s, i, arr) => arr.findIndex((x) => x.phone === s.phone) === i); }
function startOfDay(ts) { const d = new Date(ts); d.setHours(0, 0, 0, 0); return d.getTime(); }
function round(n) { return Math.round((Number(n) || 0) * 100) / 100; }
function mask(phone) { const s = String(phone || ''); return s.length > 5 ? s.slice(0, 4) + '****' + s.slice(-2) : '****'; }
function eligibility(storeId, cand, conf, now) { if (cand.churnRisk < conf.minRisk) return { ok: false, reason: 'below min risk' }; if (cand.band === 'low') return { ok: false, reason: 'low band' }; const customer = storeCRM.getCustomer(storeId, cand.phone) || {}; if (customer.promoOptIn === false) return { ok: false, reason: 'opted out' }; if (customer.status === 'blocked') return { ok: false, reason: 'blocked' }; const last = ledger.lastSentAt(storeId, cand.phone); if (last && now - new Date(last).getTime() < conf.cooldownDays * DAY) return { ok: false, reason: 'cooldown' }; return { ok: true, customer }; }
function buildMessage(storeId, cand, customer, settings) { const key = pickTemplate({ band: cand.band, frequency: cand.frequency, monetary: cand.monetary, kind: cand.kind }); const tpl = TEMPLATES[key]; const ctx = { settings: settings || {}, customer, vars: { name: cand.name || customer.name || 'Customer', loyalty_perk: LOYALTY_PERK[cand.band] || LOYALTY_PERK.medium } }; return { templateKey: key, templateLabel: tpl.label, text: renderMergeFields(tpl.body, ctx) }; }
function planCampaign(storeId = 'default_store', settings = {}, now = Date.now()) { const conf = cfg(); const sentToday = ledger.sentSince(storeId, startOfDay(now)); let budget = Math.max(0, conf.dailyCap - sentToday); const targets = []; const skipped = []; for (const cand of candidates(storeId, now)) { const e = eligibility(storeId, cand, conf, now); if (!e.ok) { skipped.push({ phone: mask(cand.phone), reason: e.reason }); continue; } if (budget <= 0) { skipped.push({ phone: mask(cand.phone), reason: 'daily cap reached' }); continue; } const msg = buildMessage(storeId, cand, e.customer, settings); targets.push({ phone: cand.phone, name: cand.name || '', band: cand.band, churnRisk: cand.churnRisk, revenueAtRisk: cand.revenueAtRisk, recencyDays: cand.recencyDays, reasons: cand.reasons || [], templateKey: msg.templateKey, message: msg.text }); budget -= 1; } return { id: newId(), storeId, createdAt: new Date(now).toISOString(), status: 'planned', mode: conf.live ? 'live' : 'dry-run', config: conf, summary: { targeted: targets.length, skipped: skipped.length, revenueAtRiskTargeted: round(targets.reduce((s, t) => s + (t.revenueAtRisk || 0), 0)), sentToday, dailyCap: conf.dailyCap }, targets, skipped: skipped.slice(0, 100) }; }
module.exports = { planCampaign, candidates, cfg, mask };
