// lib/anomalies/index.js — assemble metric series, score latest, persist deduped alerts.
const detector = require('./detector');
const { METRICS, toAlert } = require('./rules');
const store = require('./alertStore');
let forecasting = null; try { forecasting = require('../forecasting'); } catch {}
let storeCRM = null; try { storeCRM = require('../storeCRM'); } catch {}
let churnModel = null; try { churnModel = require('../analyticsInsights/churnModel'); } catch {}
const DAY = 86400000;
function dayKey(ts) { return new Date(ts).toISOString().slice(0, 10); }
function last30Keys(now) { const out = []; for (let i = 29; i >= 0; i--) out.push(dayKey(now - i * DAY)); return out; }
function buildSeries(storeId, now) { const series = { revenue: [], orders: [], newCustomers: [], failedSends: [] }; if (forecasting) { try { const s = forecasting.buildSeries(storeId, now); series.revenue = s.revenue || []; series.orders = s.orders || []; } catch {} } if (storeCRM) { const customers = storeCRM.getAllCustomers(storeId) || []; const newByDay = {}, failByDay = {}; for (const c of customers) { if (c.firstContact) { const k = dayKey(c.firstContact); newByDay[k] = (newByDay[k] || 0) + 1; } const ints = storeCRM.getCustomerInteractions(storeId, c.phone, 200) || []; for (const i of ints) { if (!i.ts) continue; if (i.type === 'send_failed' || i.type === 'failed' || i.status === 'failed') { const k = dayKey(i.ts); failByDay[k] = (failByDay[k] || 0) + 1; } } } const span = series.revenue.length ? series.revenue.map((p) => p.date) : last30Keys(now); series.newCustomers = span.map((d) => ({ date: d, value: newByDay[d] || 0 })); series.failedSends = span.map((d) => ({ date: d, value: failByDay[d] || 0 })); } return series; }
function scan(storeId = 'default_store', now = Date.now()) { const series = buildSeries(storeId, now); const found = []; for (const metricKey of ['revenue', 'orders', 'newCustomers', 'failedSends']) { const cfg = METRICS[metricKey]; const s = series[metricKey] || []; if (s.length < 11) continue; const score = detector.scoreLatest(s, { window: 30, minHistory: 10 }); const alert = score ? toAlert(metricKey, { ...score, threshold: cfg.threshold }) : null; if (alert) found.push(alert); } if (churnModel && storeCRM) { try { const customers = storeCRM.getAllCustomers(storeId) || []; const scores = churnModel.buildScores(customers, now); const atRisk = scores.bands ? scores.bands.high : 0; const total = scores.customersScored || customers.length || 1; const sharePct = (atRisk / total) * 100; if (sharePct >= 25 && atRisk >= 5) found.push({ metric: 'churnRisk', label: 'Customers at risk', date: dayKey(now), value: atRisk, baseline: Math.round(total * 0.1), z: null, direction: 'spike', deltaPct: null, severity: sharePct >= 40 ? 'critical' : 'warning', good: false, headline: `${atRisk} customers (${Math.round(sharePct)}% of base) are now high churn-risk` }); } catch {} } const fresh = store.addNew(storeId, found); return { scanned: found.length, fresh, all: found }; }
function listAlerts(storeId, opts) { return store.list(storeId, opts); }
function acknowledge(key) { return store.acknowledge(key); }
module.exports = { scan, listAlerts, acknowledge, buildSeries };
