// lib/securityGateway/index.js — Barrel export for the Security Gateway Command Center.
module.exports = {
  config: require('./config').config,
  privacyGuard: require('./privacyGuard'),
  redactor: require('./redactor'),
  hashUtils: require('./hashUtils'),
  store: require('./store'),
  securityPolicy: require('./securityPolicy'),
  rateLimiter: require('./rateLimiter'),
  rateLimitPolicy: require('./rateLimitPolicy'),
  rateLimitKeys: require('./rateLimitKeys'),
  abuseDetector: require('./abuseDetector'),
  abuseSignals: require('./abuseSignals'),
  abuseScoring: require('./abuseScoring'),
  suspiciousActivity: require('./suspiciousActivity'),
  inputValidator: require('./inputValidator'),
  payloadSizeGuard: require('./payloadSizeGuard'),
  scopeGuard: require('./scopeGuard'),
  tenantIsolationGuard: require('./tenantIsolationGuard'),
  safetyGuard: require('./safetyGuard'),
  securityEventWriter: require('./securityEventWriter'),
  securityGateway: require('./securityGateway'),
  securityDoctor: require('./securityDoctor'),
  securityScoring: require('./securityScoring'),
  middleware: require('./middleware'),
  flowNodes: require('./flowNodes'),
  adminCommands: require('./adminCommands'),
};
