// lib/attribution/journeys.js — reconstruct conversion journeys from CRM log.
let storeCRM = null; try { storeCRM = require('../storeCRM'); } catch {}
const LOOKBACK_DAYS = Number(process.env.ATTRIBUTION_LOOKBACK_DAYS || 90);
const DAY = 86400000;
const TOUCH_TYPES = new Set(['inbound', 'reply', 'message_in', 'message_out', 'broadcast', 'campaign', 'loyalty_earn', 'loyalty_redeem', 'follow_up', 're_engagement', 'note']);
function channelOf(i, c) { return i.channel || i.source || (i.kind === 're_engagement' ? 're_engagement' : null) || (c && c.source) || 'whatsapp'; }
function campaignOf(i) { return i.campaignId || i.campaign || i.experimentId || null; }
function customerJourneys(storeId, phone, now) { if (!storeCRM) return []; const customer = storeCRM.getCustomer(storeId, phone) || {}; const ints = (storeCRM.getCustomerInteractions(storeId, phone, 500) || []).slice().sort((a, b) => new Date(a.ts).getTime() - new Date(b.ts).getTime()); const minTs = now - LOOKBACK_DAYS * DAY; const orders = ints.filter((i) => i.type === 'order' && Number(i.amount) > 0 && new Date(i.ts).getTime() >= minTs); if (!orders.length) return []; const journeys = []; for (const order of orders) { const convTime = new Date(order.ts).getTime(); const windowStart = convTime - LOOKBACK_DAYS * DAY; let touches = ints.filter((i) => { const t = new Date(i.ts).getTime(); return t <= convTime && t >= windowStart && (TOUCH_TYPES.has(i.type) || i.type === 'order'); }).map((i) => ({ ts: new Date(i.ts).getTime(), channel: channelOf(i, customer), campaign: campaignOf(i), type: i.type })); touches = touches.filter((t, idx, arr) => { if (idx === 0) return true; const p = arr[idx - 1]; return !(p.channel === t.channel && p.campaign === t.campaign); }); if (!touches.length) touches = [{ ts: convTime, channel: customer.source || 'whatsapp', campaign: null, type: 'order' }]; journeys.push({ phone, convTime, value: Number(order.amount || 0), touches }); } return journeys; }
function allJourneys(storeId, now = Date.now()) { if (!storeCRM) return []; const customers = storeCRM.getAllCustomers(storeId) || []; const out = []; for (const c of customers) { if (!c.phone) continue; for (const j of customerJourneys(storeId, c.phone, now)) out.push(j); } return out; }
module.exports = { allJourneys, customerJourneys, LOOKBACK_DAYS, TOUCH_TYPES };
