/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppZeroTouchRouteImport } from './routes/_app.zero-touch'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppWatiRouteImport } from './routes/_app.wati'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppStockRouteImport } from './routes/_app.stock'
import { Route as AppSocialRouteImport } from './routes/_app.social'
import { Route as AppSmartBroadcastRouteImport } from './routes/_app.smart-broadcast'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSchedulerRouteImport } from './routes/_app.scheduler'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppRatesRouteImport } from './routes/_app.rates'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppPublisherPostsRouteImport } from './routes/_app.publisher-posts'
import { Route as AppPublisherAnalyticsRouteImport } from './routes/_app.publisher-analytics'
import { Route as AppPublisherRouteImport } from './routes/_app.publisher'
import { Route as AppPlansRouteImport } from './routes/_app.plans'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppMarketplacesRouteImport } from './routes/_app.marketplaces'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppGiveawaysRouteImport } from './routes/_app.giveaways'
import { Route as AppFlowsRouteImport } from './routes/_app.flows'
import { Route as AppDealersRouteImport } from './routes/_app.dealers'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppConnectionsRouteImport } from './routes/_app.connections'
import { Route as AppCommerceRouteImport } from './routes/_app.commerce'
import { Route as AppCodeRouteImport } from './routes/_app.code'
import { Route as AppChannelsRouteImport } from './routes/_app.channels'
import { Route as AppCatalogRouteImport } from './routes/_app.catalog'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppBroadcastRouteImport } from './routes/_app.broadcast'
import { Route as AppBotsRouteImport } from './routes/_app.bots'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as ApiPublicCronDispatchRouteImport } from './routes/api/public/cron/dispatch'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppZeroTouchRoute = AppZeroTouchRouteImport.update({
  id: '/zero-touch',
  path: '/zero-touch',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppWatiRoute = AppWatiRouteImport.update({
  id: '/wati',
  path: '/wati',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartBroadcastRoute = AppSmartBroadcastRouteImport.update({
  id: '/smart-broadcast',
  path: '/smart-broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppRatesRoute = AppRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPublisherPostsRoute = AppPublisherPostsRouteImport.update({
  id: '/publisher-posts',
  path: '/publisher-posts',
  getParentRoute: () => AppRoute,
} as any)
const AppPublisherAnalyticsRoute = AppPublisherAnalyticsRouteImport.update({
  id: '/publisher-analytics',
  path: '/publisher-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPublisherRoute = AppPublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplacesRoute = AppMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppGiveawaysRoute = AppGiveawaysRouteImport.update({
  id: '/giveaways',
  path: '/giveaways',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsRoute = AppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AppRoute,
} as any)
const AppDealersRoute = AppDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppCommerceRoute = AppCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsRoute = AppBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCronDispatchRoute = ApiPublicCronDispatchRouteImport.update({
  id: '/api/public/cron/dispatch',
  path: '/api/public/cron/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/bots': typeof AppBotsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/campaigns': typeof AppCampaignsRoute
  '/catalog': typeof AppCatalogRoute
  '/channels': typeof AppChannelsRoute
  '/code': typeof AppCodeRoute
  '/commerce': typeof AppCommerceRoute
  '/connections': typeof AppConnectionsRoute
  '/customers': typeof AppCustomersRoute
  '/dealers': typeof AppDealersRoute
  '/flows': typeof AppFlowsRoute
  '/giveaways': typeof AppGiveawaysRoute
  '/groups': typeof AppGroupsRoute
  '/inbox': typeof AppInboxRoute
  '/marketplaces': typeof AppMarketplacesRoute
  '/orders': typeof AppOrdersRoute
  '/payments': typeof AppPaymentsRoute
  '/plans': typeof AppPlansRoute
  '/publisher': typeof AppPublisherRoute
  '/publisher-analytics': typeof AppPublisherAnalyticsRoute
  '/publisher-posts': typeof AppPublisherPostsRoute
  '/purchases': typeof AppPurchasesRoute
  '/rates': typeof AppRatesRoute
  '/sales': typeof AppSalesRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/smart-broadcast': typeof AppSmartBroadcastRoute
  '/social': typeof AppSocialRoute
  '/stock': typeof AppStockRoute
  '/team': typeof AppTeamRoute
  '/wati': typeof AppWatiRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/zero-touch': typeof AppZeroTouchRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/bots': typeof AppBotsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/campaigns': typeof AppCampaignsRoute
  '/catalog': typeof AppCatalogRoute
  '/channels': typeof AppChannelsRoute
  '/code': typeof AppCodeRoute
  '/commerce': typeof AppCommerceRoute
  '/connections': typeof AppConnectionsRoute
  '/customers': typeof AppCustomersRoute
  '/dealers': typeof AppDealersRoute
  '/flows': typeof AppFlowsRoute
  '/giveaways': typeof AppGiveawaysRoute
  '/groups': typeof AppGroupsRoute
  '/inbox': typeof AppInboxRoute
  '/marketplaces': typeof AppMarketplacesRoute
  '/orders': typeof AppOrdersRoute
  '/payments': typeof AppPaymentsRoute
  '/plans': typeof AppPlansRoute
  '/publisher': typeof AppPublisherRoute
  '/publisher-analytics': typeof AppPublisherAnalyticsRoute
  '/publisher-posts': typeof AppPublisherPostsRoute
  '/purchases': typeof AppPurchasesRoute
  '/rates': typeof AppRatesRoute
  '/sales': typeof AppSalesRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/smart-broadcast': typeof AppSmartBroadcastRoute
  '/social': typeof AppSocialRoute
  '/stock': typeof AppStockRoute
  '/team': typeof AppTeamRoute
  '/wati': typeof AppWatiRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/zero-touch': typeof AppZeroTouchRoute
  '/': typeof AppIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/bots': typeof AppBotsRoute
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/channels': typeof AppChannelsRoute
  '/_app/code': typeof AppCodeRoute
  '/_app/commerce': typeof AppCommerceRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dealers': typeof AppDealersRoute
  '/_app/flows': typeof AppFlowsRoute
  '/_app/giveaways': typeof AppGiveawaysRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/marketplaces': typeof AppMarketplacesRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/publisher': typeof AppPublisherRoute
  '/_app/publisher-analytics': typeof AppPublisherAnalyticsRoute
  '/_app/publisher-posts': typeof AppPublisherPostsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/rates': typeof AppRatesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/scheduler': typeof AppSchedulerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/smart-broadcast': typeof AppSmartBroadcastRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/wati': typeof AppWatiRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/zero-touch': typeof AppZeroTouchRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/analytics'
    | '/audit'
    | '/bots'
    | '/broadcast'
    | '/campaigns'
    | '/catalog'
    | '/channels'
    | '/code'
    | '/commerce'
    | '/connections'
    | '/customers'
    | '/dealers'
    | '/flows'
    | '/giveaways'
    | '/groups'
    | '/inbox'
    | '/marketplaces'
    | '/orders'
    | '/payments'
    | '/plans'
    | '/publisher'
    | '/publisher-analytics'
    | '/publisher-posts'
    | '/purchases'
    | '/rates'
    | '/sales'
    | '/scheduler'
    | '/settings'
    | '/smart-broadcast'
    | '/social'
    | '/stock'
    | '/team'
    | '/wati'
    | '/whatsapp'
    | '/zero-touch'
    | '/api/public/cron/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/unauthorized'
    | '/analytics'
    | '/audit'
    | '/bots'
    | '/broadcast'
    | '/campaigns'
    | '/catalog'
    | '/channels'
    | '/code'
    | '/commerce'
    | '/connections'
    | '/customers'
    | '/dealers'
    | '/flows'
    | '/giveaways'
    | '/groups'
    | '/inbox'
    | '/marketplaces'
    | '/orders'
    | '/payments'
    | '/plans'
    | '/publisher'
    | '/publisher-analytics'
    | '/publisher-posts'
    | '/purchases'
    | '/rates'
    | '/sales'
    | '/scheduler'
    | '/settings'
    | '/smart-broadcast'
    | '/social'
    | '/stock'
    | '/team'
    | '/wati'
    | '/whatsapp'
    | '/zero-touch'
    | '/'
    | '/api/public/cron/dispatch'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/unauthorized'
    | '/_app/analytics'
    | '/_app/audit'
    | '/_app/bots'
    | '/_app/broadcast'
    | '/_app/campaigns'
    | '/_app/catalog'
    | '/_app/channels'
    | '/_app/code'
    | '/_app/commerce'
    | '/_app/connections'
    | '/_app/customers'
    | '/_app/dealers'
    | '/_app/flows'
    | '/_app/giveaways'
    | '/_app/groups'
    | '/_app/inbox'
    | '/_app/marketplaces'
    | '/_app/orders'
    | '/_app/payments'
    | '/_app/plans'
    | '/_app/publisher'
    | '/_app/publisher-analytics'
    | '/_app/publisher-posts'
    | '/_app/purchases'
    | '/_app/rates'
    | '/_app/sales'
    | '/_app/scheduler'
    | '/_app/settings'
    | '/_app/smart-broadcast'
    | '/_app/social'
    | '/_app/stock'
    | '/_app/team'
    | '/_app/wati'
    | '/_app/whatsapp'
    | '/_app/zero-touch'
    | '/_app/'
    | '/api/public/cron/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiPublicCronDispatchRoute: typeof ApiPublicCronDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/zero-touch': {
      id: '/_app/zero-touch'
      path: '/zero-touch'
      fullPath: '/zero-touch'
      preLoaderRoute: typeof AppZeroTouchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wati': {
      id: '/_app/wati'
      path: '/wati'
      fullPath: '/wati'
      preLoaderRoute: typeof AppWatiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/smart-broadcast': {
      id: '/_app/smart-broadcast'
      path: '/smart-broadcast'
      fullPath: '/smart-broadcast'
      preLoaderRoute: typeof AppSmartBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduler': {
      id: '/_app/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rates': {
      id: '/_app/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AppRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publisher-posts': {
      id: '/_app/publisher-posts'
      path: '/publisher-posts'
      fullPath: '/publisher-posts'
      preLoaderRoute: typeof AppPublisherPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publisher-analytics': {
      id: '/_app/publisher-analytics'
      path: '/publisher-analytics'
      fullPath: '/publisher-analytics'
      preLoaderRoute: typeof AppPublisherAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publisher': {
      id: '/_app/publisher'
      path: '/publisher'
      fullPath: '/publisher'
      preLoaderRoute: typeof AppPublisherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplaces': {
      id: '/_app/marketplaces'
      path: '/marketplaces'
      fullPath: '/marketplaces'
      preLoaderRoute: typeof AppMarketplacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/giveaways': {
      id: '/_app/giveaways'
      path: '/giveaways'
      fullPath: '/giveaways'
      preLoaderRoute: typeof AppGiveawaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows': {
      id: '/_app/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AppFlowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dealers': {
      id: '/_app/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof AppDealersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commerce': {
      id: '/_app/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof AppCommerceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/code': {
      id: '/_app/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots': {
      id: '/_app/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AppBotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cron/dispatch': {
      id: '/api/public/cron/dispatch'
      path: '/api/public/cron/dispatch'
      fullPath: '/api/public/cron/dispatch'
      preLoaderRoute: typeof ApiPublicCronDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBotsRoute: typeof AppBotsRoute
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppCodeRoute: typeof AppCodeRoute
  AppCommerceRoute: typeof AppCommerceRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDealersRoute: typeof AppDealersRoute
  AppFlowsRoute: typeof AppFlowsRoute
  AppGiveawaysRoute: typeof AppGiveawaysRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMarketplacesRoute: typeof AppMarketplacesRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPlansRoute: typeof AppPlansRoute
  AppPublisherRoute: typeof AppPublisherRoute
  AppPublisherAnalyticsRoute: typeof AppPublisherAnalyticsRoute
  AppPublisherPostsRoute: typeof AppPublisherPostsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppRatesRoute: typeof AppRatesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmartBroadcastRoute: typeof AppSmartBroadcastRoute
  AppSocialRoute: typeof AppSocialRoute
  AppStockRoute: typeof AppStockRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWatiRoute: typeof AppWatiRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppZeroTouchRoute: typeof AppZeroTouchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBotsRoute: AppBotsRoute,
  AppBroadcastRoute: AppBroadcastRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppCodeRoute: AppCodeRoute,
  AppCommerceRoute: AppCommerceRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDealersRoute: AppDealersRoute,
  AppFlowsRoute: AppFlowsRoute,
  AppGiveawaysRoute: AppGiveawaysRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppInboxRoute: AppInboxRoute,
  AppMarketplacesRoute: AppMarketplacesRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPlansRoute: AppPlansRoute,
  AppPublisherRoute: AppPublisherRoute,
  AppPublisherAnalyticsRoute: AppPublisherAnalyticsRoute,
  AppPublisherPostsRoute: AppPublisherPostsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppRatesRoute: AppRatesRoute,
  AppSalesRoute: AppSalesRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmartBroadcastRoute: AppSmartBroadcastRoute,
  AppSocialRoute: AppSocialRoute,
  AppStockRoute: AppStockRoute,
  AppTeamRoute: AppTeamRoute,
  AppWatiRoute: AppWatiRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppZeroTouchRoute: AppZeroTouchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiPublicCronDispatchRoute: ApiPublicCronDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
