// lib/tenantIsolation/index.js — Barrel export for the Multi-Tenant Data Isolation Command Center.
module.exports = {
  config: require('./config').config,
  store: require('./store'),
  redactor: require('./redactor'),
  privacyGuard: require('./privacyGuard'),
  safetyGuard: require('./safetyGuard'),
  piiPatterns: require('./piiPatterns'),
  secretPatterns: require('./secretPatterns'),
  boundaryContext: require('./boundaryContext'),
  boundaryPolicy: require('./boundaryPolicy'),
  defaultBoundaryPolicies: require('./defaultBoundaryPolicies'),
  policyRegistry: require('./policyRegistry'),
  isolationEvaluator: require('./isolationEvaluator'),
  payloadScanner: require('./payloadScanner'),
  responseLeakDetector: require('./responseLeakDetector'),
  leakDetector: require('./leakDetector'),
  routeRiskCatalog: require('./routeRiskCatalog'),
  routeBoundaryScanner: require('./routeBoundaryScanner'),
  dataShapeCatalog: require('./dataShapeCatalog'),
  storeBoundaryScanner: require('./storeBoundaryScanner'),
  simulationFixtures: require('./simulationFixtures'),
  crossTenantSimulation: require('./crossTenantSimulation'),
  isolationScoring: require('./isolationScoring'),
  isolationDoctor: require('./isolationDoctor'),
  middleware: require('./middleware'),
  flowNodes: require('./flowNodes'),
  adminCommands: require('./adminCommands'),
};
