// lib/unifiedSetup/stepDefinitions.js — Canonical list of onboarding setup steps.
// Steps backed by an existing module reference a connectorId; pure-config steps don't.

module.exports = [
  { id: 'business_profile', title: 'Business Profile', category: 'foundation', required: true },
  { id: 'tenant_registry', title: 'Tenant Registry', category: 'foundation', required: false },
  { id: 'admin_auth', title: 'Admin Auth / RBAC', category: 'security', required: true, connectorId: 'admin_auth' },
  { id: 'security_scan', title: 'Security Scan', category: 'security', required: true, connectorId: 'security_scan' },
  { id: 'whatsapp_local', title: 'WhatsApp (Local)', category: 'messaging', required: false, connectorId: 'whatsapp_local' },
  { id: 'whatsapp_cloud', title: 'WhatsApp Cloud API', category: 'messaging', required: false, connectorId: 'whatsapp_cloud' },
  { id: 'whatsapp_channels', title: 'WhatsApp Channels', category: 'messaging', required: false, connectorId: 'channel_automation' },
  { id: 'ecommerce', title: 'Ecommerce', category: 'commerce', required: false, connectorId: 'ecommerce' },
  { id: 'payments', title: 'Payments', category: 'commerce', required: false, connectorId: 'payments' },
  { id: 'social', title: 'Social Media', category: 'marketing', required: false, connectorId: 'social' },
  { id: 'telegram', title: 'Telegram', category: 'messaging', required: false },
  { id: 'google_sheets', title: 'Google Sheets', category: 'integrations', required: false, connectorId: 'google_sheets' },
  { id: 'n8n', title: 'n8n Automation', category: 'integrations', required: false, connectorId: 'google_sheets' },
  { id: 'ai_providers', title: 'AI Providers', category: 'ai', required: false, connectorId: 'ai_providers' },
  { id: 'voice_ai', title: 'Voice AI', category: 'ai', required: false, connectorId: 'voice_ai' },
  { id: 'channel_automation', title: 'Channel Automation', category: 'automation', required: false, connectorId: 'channel_automation' },
  { id: 'group_commerce', title: 'Group Commerce', category: 'commerce', required: false, connectorId: 'group_commerce' },
  { id: 'marketplace_intelligence', title: 'Marketplace Intelligence', category: 'intelligence', required: false, connectorId: 'marketplace_intelligence' },
  { id: 'customer_360', title: 'Customer 360', category: 'crm', required: false, connectorId: 'customer_360' },
  { id: 'agent_deployment', title: 'AI Agent Deployment', category: 'ai', required: false, connectorId: 'agent_deployment' },
  { id: 'playbooks', title: 'Playbooks / SOPs', category: 'ops', required: false, connectorId: 'playbooks' },
  { id: 'owner_command', title: 'Owner Command', category: 'ops', required: false, connectorId: 'owner_command' },
  { id: 'launch_center', title: 'Launch Center', category: 'launch', required: true, connectorId: 'launch_center' },
  { id: 'backup', title: 'Backup', category: 'ops', required: false },
  { id: 'monitoring', title: 'Monitoring', category: 'ops', required: false },
  { id: 'pilot_launch', title: 'Pilot Launch', category: 'launch', required: true },
];
