// lib/unifiedSetup/taskTemplates.js — Templates for onboarding tasks generated from missing setup.

module.exports = {
  business_profile: { title: 'Complete your business profile', priority: 'high',
    instructions: 'Set business type, country, timezone, currency and goals.', actionRoute: '/unified-setup.html' },
  admin_auth: { title: 'Configure admin auth (JWT_SECRET)', priority: 'high',
    instructions: 'Set a strong JWT_SECRET in .env and create the admin login.', actionRoute: '/unified-setup.html' },
  security_scan: { title: 'Run the security scan', priority: 'high',
    instructions: 'Run npm run secret:scan and resolve any findings.', actionRoute: null },
  whatsapp_local: { title: 'Connect WhatsApp (local)', priority: 'medium',
    instructions: 'Scan the WhatsApp QR to link the local session. Manual action required.', actionRoute: null },
  whatsapp_cloud: { title: 'Connect WhatsApp Cloud API', priority: 'medium',
    instructions: 'Add WHATSAPP_CLOUD_TOKEN + WHATSAPP_PHONE_NUMBER_ID from Meta.', actionRoute: '/unified-setup.html' },
  ecommerce: { title: 'Set up your ecommerce catalog', priority: 'medium',
    instructions: 'Add products / connect your store.', actionRoute: '/store.html' },
  payments: { title: 'Configure payment parsing', priority: 'medium',
    instructions: 'Add PAYMENT_IMAP_* credentials for automatic payment detection.', actionRoute: '/unified-setup.html' },
  social: { title: 'Connect social platforms', priority: 'low',
    instructions: 'Add Meta/LinkedIn/TikTok tokens to enable posting.', actionRoute: '/unified-setup.html' },
  ai_providers: { title: 'Add an AI provider key', priority: 'medium',
    instructions: 'Add at least one of OPENAI/ANTHROPIC/GEMINI keys to enable AI features.', actionRoute: '/unified-setup.html' },
  voice_ai: { title: 'Review Voice AI setup', priority: 'low',
    instructions: 'Voice AI runs dry-run by default. Add a TTS/STT key to go live later.', actionRoute: '/voice-ai.html' },
  launch_center: { title: 'Run launch readiness', priority: 'high',
    instructions: 'Run npm run launch:check before pilot.', actionRoute: null },
  pilot_launch: { title: 'Complete the pilot launch checklist', priority: 'high',
    instructions: 'Verify all required steps, then start your pilot.', actionRoute: '/unified-setup.html' },
};
