const PRESETS = {
  ai_tools_reseller: {
      id: 'ai_tools_reseller', label: 'AI Tools Reseller',
      recommendedModules: ['whatsapp', 'catalog', 'payments', 'orders', 'customer360', 'ownerCommand', 'agentDeployment',
'channelAutomation'],
    recommendedAgents: ['sales_agent', 'support_agent', 'payment_agent', 'renewal_agent'],
      recommendedPlaybooks: ['payment_verification', 'order_delivery', 'sales_followup', 'renewal_reminder'],
      recommendedChannelRules: ['promo_post_draft', 'restock_announcement'],
      recommendedCustomerTags: ['new_lead', 'paid', 'renewal_due', 'churned'],
      recommendedOwnerDigest: 'daily_sales_and_renewals',
      recommendedVoiceTemplates: ['order_confirmation', 'renewal_reminder'],
      recommendedEcommerceFields: ['product_name', 'price', 'validity', 'delivery_type'],
      recommendedPaymentMethods: ['easypaisa', 'jazzcash', 'bank_transfer'],
      requiredChecklist: ['business_profile', 'whatsapp_connection', 'admin_numbers', 'ai_provider', 'payment_methods'],
      optionalChecklist: ['channel_automation', 'customer360_privacy', 'owner_command'],
      launchBlockers: ['whatsapp_connection', 'admin_numbers'],
  },
  ecommerce_store: {
      id: 'ecommerce_store', label: 'Ecommerce Store',
      recommendedModules: ['ecommerce', 'catalog', 'orders', 'payments', 'channelAutomation', 'customer360',
'ownerCommand'],
    recommendedAgents: ['sales_agent', 'support_agent', 'ecommerce_agent'],
      recommendedPlaybooks: ['order_fulfillment', 'payment_reminder', 'abandoned_cart', 'customer_followup'],
      recommendedChannelRules: ['product_posting', 'daily_offers'],
      recommendedCustomerTags: ['cart_abandoned', 'repeat_buyer', 'vip'],
      recommendedOwnerDigest: 'daily_orders_and_revenue',
      recommendedVoiceTemplates: ['order_status'],
      recommendedEcommerceFields: ['sku', 'price', 'stock', 'category'],
      recommendedPaymentMethods: ['cod', 'card', 'bank_transfer'],
      requiredChecklist: ['business_profile', 'whatsapp_connection', 'ecommerce_connection', 'payment_methods'],
      optionalChecklist: ['social_connections', 'channel_automation', 'customer360_privacy'],
      launchBlockers: ['ecommerce_connection', 'payment_methods'],
  },
  wholesale_dealer: {
      id: 'wholesale_dealer', label: 'Dealer / Wholesale Business',
      recommendedModules: ['marketplaceIntelligence', 'groupCommerce', 'catalog', 'ownerCommand'],
      recommendedAgents: ['seller_intelligence_agent', 'buyer_matching_agent', 'marketplace_advisor_agent'],
      recommendedPlaybooks: ['daily_price_digest', 'stock_radar', 'seller_buyer_match'],
      recommendedChannelRules: ['price_drop_alert'],
      recommendedCustomerTags: ['seller', 'buyer', 'high_trust', 'risk'],
      recommendedOwnerDigest: 'daily_price_and_opportunity',
      recommendedVoiceTemplates: [],

 recommendedEcommerceFields: ['sku', 'price', 'stock', 'city'],
 recommendedPaymentMethods: ['bank_transfer'],
 requiredChecklist: ['business_profile', 'whatsapp_connection', 'admin_numbers'],
 optionalChecklist: ['channel_automation', 'owner_command'],
 launchBlockers: ['whatsapp_connection'],
},
education_scholarship: {
 id: 'education_scholarship', label: 'Education / Scholarship Channel',
 recommendedModules: ['channelAutomation', 'flowStudio', 'ownerCommand'],
 recommendedAgents: ['channel_publisher_agent', 'social_caption_agent'],
 recommendedPlaybooks: ['content_approval_queue', 'daily_digest', 'social_republish'],
 recommendedChannelRules: ['rss_source_ingest', 'approval_queue'],
 recommendedCustomerTags: ['subscriber'],
 recommendedOwnerDigest: 'daily_content_summary',
 recommendedVoiceTemplates: [],
 recommendedEcommerceFields: [],
 recommendedPaymentMethods: [],
 requiredChecklist: ['business_profile', 'channel_automation'],
 optionalChecklist: ['social_connections'],
 launchBlockers: ['channel_automation'],
},
jobs_recruitment: {
 id: 'jobs_recruitment', label: 'Jobs Channel',
 recommendedModules: ['channelAutomation', 'flowStudio', 'ownerCommand'],
 recommendedAgents: ['channel_publisher_agent'],
 recommendedPlaybooks: ['category_routing', 'duplicate_detector', 'channel_post'],
 recommendedChannelRules: ['rss_scrape_checklist', 'telegram_bridge'],
 recommendedCustomerTags: ['job_seeker', 'employer'],
 recommendedOwnerDigest: 'daily_jobs_summary',
 recommendedVoiceTemplates: [],
 recommendedEcommerceFields: [],
 recommendedPaymentMethods: [],
 requiredChecklist: ['business_profile', 'channel_automation'],
 optionalChecklist: ['social_connections'],
 launchBlockers: ['channel_automation'],
},
digital_services_agency: {
 id: 'digital_services_agency', label: 'Digital Agency',
 recommendedModules: ['inbox', 'ownerCommand', 'agentDeployment', 'voiceAI'],
 recommendedAgents: ['sales_agent', 'support_agent', 'voice_agent'],
 recommendedPlaybooks: ['lead_inbox', 'proposal_followup', 'client_onboarding', 'support_sop'],
 recommendedChannelRules: [],
 recommendedCustomerTags: ['lead', 'client', 'proposal_sent'],
 recommendedOwnerDigest: 'daily_leads_and_followups',
 recommendedVoiceTemplates: ['lead_followup'],
 recommendedEcommerceFields: [],
 recommendedPaymentMethods: ['bank_transfer', 'card'],
 requiredChecklist: ['business_profile', 'whatsapp_connection', 'ai_provider'],
 optionalChecklist: ['voice_ai', 'owner_command'],
 launchBlockers: ['whatsapp_connection'],
},
restaurant_food: {
 id: 'restaurant_food', label: 'Restaurant / Food',
 recommendedModules: ['catalog', 'orders', 'channelAutomation', 'customer360'],
 recommendedAgents: ['sales_agent', 'support_agent'],
 recommendedPlaybooks: ['order_alert', 'customer_followup', 'daily_offers'],
 recommendedChannelRules: ['menu_post', 'broadcast_draft'],

      recommendedCustomerTags: ['regular', 'new'],
      recommendedOwnerDigest: 'daily_orders',
      recommendedVoiceTemplates: ['order_ready'],
      recommendedEcommerceFields: ['item_name', 'price', 'category'],
      recommendedPaymentMethods: ['cod', 'easypaisa', 'jazzcash'],
      requiredChecklist: ['business_profile', 'whatsapp_connection', 'catalog'],
      optionalChecklist: ['channel_automation'],
      launchBlockers: ['whatsapp_connection'],
    },
    real_estate: {
      id: 'real_estate', label: 'Real Estate',
      recommendedModules: ['inbox', 'channelAutomation', 'voiceAI', 'customer360'],
      recommendedAgents: ['sales_agent', 'voice_agent'],
      recommendedPlaybooks: ['property_listing_draft', 'buyer_inquiry_tracking', 'voice_followup'],
      recommendedChannelRules: ['listing_post'],
      recommendedCustomerTags: ['buyer', 'seller', 'investor'],
      recommendedOwnerDigest: 'daily_inquiries',
      recommendedVoiceTemplates: ['property_followup'],
      recommendedEcommerceFields: ['property_type', 'price', 'location', 'size'],
      recommendedPaymentMethods: ['bank_transfer'],
      requiredChecklist: ['business_profile', 'whatsapp_connection'],
      optionalChecklist: ['voice_ai', 'social_connections'],
      launchBlockers: ['whatsapp_connection'],
    },
    sticker_channel: {
      id: 'sticker_channel', label: 'Sticker / Content Channel',
      recommendedModules: ['channelAutomation', 'flowStudio'],
      recommendedAgents: ['channel_publisher_agent', 'social_caption_agent'],
      recommendedPlaybooks: ['source_channel_rules', 'caption_cleaner', 'queue_approval', 'social_repost'],
      recommendedChannelRules: ['source_ingest', 'branding', 'approval_queue'],
      recommendedCustomerTags: ['subscriber'],
      recommendedOwnerDigest: 'daily_content_summary',
      recommendedVoiceTemplates: [],
      recommendedEcommerceFields: [],
      recommendedPaymentMethods: [],
      requiredChecklist: ['business_profile', 'channel_automation'],
      optionalChecklist: ['social_connections'],
      launchBlockers: ['channel_automation'],
    },
    custom_business: {
      id: 'custom_business', label: 'Custom Business',
      recommendedModules: ['whatsapp'],
      recommendedAgents: ['support_agent'],
      recommendedPlaybooks: ['daily_routine'],
      recommendedChannelRules: [],
      recommendedCustomerTags: ['lead'],
      recommendedOwnerDigest: 'daily_summary',
      recommendedVoiceTemplates: [],
      recommendedEcommerceFields: [],
      recommendedPaymentMethods: [],
      requiredChecklist: ['business_profile'],
      optionalChecklist: ['whatsapp_connection'],
      launchBlockers: [],
    },
};


// map every business type to a preset (fallback custom)

function presetForBusinessType(bt) {
   if (PRESETS[bt]) return PRESETS[bt];
   const map = {
     fashion_clothing: 'ecommerce_store', mobile_accessories: 'ecommerce_store',
     local_shop: 'ecommerce_store', coaching_training: 'digital_services_agency',
     islamic_content: 'sticker_channel', affiliate_marketing: 'ai_tools_reseller',
   };
   return PRESETS[map[bt] || 'custom_business'];
}


function list() { return Object.values(PRESETS).map(({ id, label, recommendedModules }) => ({ id, label,
recommendedModules })); }
function get(id) { return PRESETS[id] || null; }

module.exports = { PRESETS, list, get, presetForBusinessType };
