'use strict';
/**
 * replySuggestions.js — Inbox Feature #3: AI-suggested replies for human agents.
 *
 * In the inbox (#inbox1), an agent staring at a thread wants help, not autopilot. This SUGGESTS
 * 2-3 replies for the latest customer message — grounded in the knowledge base (#support2) and the
 * customer's 360 context (#crm1), generated by the app's Ollama brain — plus the best-matching
 * canned replies (#inbox2) as instant safe options. The agent picks/edits then sends. Nothing is
 * auto-sent: this augments the human, it doesn't replace them.
 *
 * All capabilities are injected so it's decoupled and testable.
 */

let aiBrain = null;
try { aiBrain = require('../../ai/aiBrain'); } catch { aiBrain = null; }

let getThread = null;    // (phone) => { messages:[{dir,text}] }
let getProfile = null;   // (phone) => profile
let kbSearch = null;     // (query) => string[]
let cannedSearch = null; // (query) => [{ shortcut, body }]
let aiCall = null;       // async (prompt) => string
function configure(h = {}) {
  if (typeof h.getThread === 'function') getThread = h.getThread;
  if (typeof h.getProfile === 'function') getProfile = h.getProfile;
  if (typeof h.kbSearch === 'function') kbSearch = h.kbSearch;
  if (typeof h.cannedSearch === 'function') cannedSearch = h.cannedSearch;
  if (typeof h.aiCall === 'function') aiCall = h.aiCall;
}

function lastCustomerMessage(thread) {
  if (!thread || !Array.isArray(thread.messages)) return '';
  for (let i = thread.messages.length - 1; i >= 0; i--) {
    if (thread.messages[i].dir === 'in') return thread.messages[i].text || '';
  }
  return '';
}

async function runAi(prompt) {
  if (aiCall) return aiCall(prompt);
  if (aiBrain && typeof aiBrain.processPrompt === 'function') return aiBrain.processPrompt(prompt);
  throw new Error('no AI');
}

function profileLine(phone) {
  if (!getProfile) return '';
  const p = getProfile(phone);
  if (!p) return 'New/unknown customer.';
  const s = p.stats || {};
  return `${p.name || phone} — stage ${p.stage || 'lead'}, ${s.orderCount || 0} orders, spent ${s.totalSpent || 0}.`;
}

/**
 * Suggest replies for a thread. Returns { question, suggestions:[{source,text}] }.
 * source: 'canned' | 'ai'. Never sends anything.
 */
async function suggest(phone, opts = {}) {
  if (!phone) throw new Error('phone required');
  const thread = getThread ? getThread(phone) : null;
  const question = opts.message || lastCustomerMessage(thread);
  if (!question) return { question: '', suggestions: [] };

  const suggestions = [];

  // 1) canned replies that match (instant, safe)
  if (cannedSearch) {
    try {
      for (const c of (cannedSearch(question) || []).slice(0, 2)) {
        suggestions.push({ source: 'canned', shortcut: c.shortcut, text: c.body });
      }
    } catch { /* ignore */ }
  }

  // 2) AI suggestions grounded in KB + profile
  try {
    const kb = (kbSearch ? (kbSearch(question) || []) : []).slice(0, 5);
    const prompt = [
      'You are helping a human support agent reply on WhatsApp. Suggest 2 short, friendly reply options.',
      'Ground them ONLY in the knowledge base and customer context. If unsure, suggest asking a clarifying question. Do not invent facts.',
      'Return each option on its own line, prefixed with "- ".',
      '',
      `Customer context: ${profileLine(phone)}`,
      `Knowledge base:\n${kb.length ? kb.map((k, i) => `[${i + 1}] ${k}`).join('\n') : '(none)'}`,
      '',
      `Customer said: "${question}"`,
      'Reply options:'
    ].join('\n');
    const raw = String(await runAi(prompt) || '').trim();
    for (const line of raw.split('\n')) {
      const t = line.replace(/^[-*\d.\s]+/, '').trim();
      if (t) suggestions.push({ source: 'ai', text: t });
    }
  } catch { /* AI optional — canned still useful */ }

  // de-dupe + cap
  const seen = new Set();
  const out = [];
  for (const s of suggestions) {
    const key = s.text.toLowerCase().slice(0, 60);
    if (s.text && !seen.has(key)) { seen.add(key); out.push(s); }
    if (out.length >= 4) break;
  }
  return { question, suggestions: out };
}

module.exports = { configure, suggest };
