// lib/groupCommerce/analytics.js - Group Activity Analytics & Daily Digest
const store = require('./store');
const catalog = require('./catalog');
const groupRegistry = require('./groupRegistry');

function activityStats(groupId) {
  const history = (store.readHistory().history || []).filter(h => h.groupId === groupId);
  const byType = {};
  let sellerMsgs = 0;
  let buyerMsgs = 0;

  history.forEach(h => {
    byType[h.type] = (byType[h.type] || 0) + 1;
    const intent = h.analyzed && h.analyzed.roleIntent;
    if (intent === 'seller') sellerMsgs += 1;
    if (intent === 'buyer') buyerMsgs += 1;
  });

  return {
    success: true,
    groupId,
    totalEvents: history.length,
    byType,
    sellerMessages: sellerMsgs,
    buyerMessages: buyerMsgs
  };
}

function dailyDigest(groupId) {
  const group = groupRegistry.getGroup(groupId);
  const items = catalog.listGroupCatalog(groupId);
  const stats = activityStats(groupId);
  const lowStock = items.filter(i => (i.stock || 0) > 0 && (i.stock || 0) <= 3);

  let text = '📊 *DAILY GROUP DIGEST* — ' + (group ? group.groupName : groupId) + '\n';
  text += '🗓️ ' + new Date().toDateString() + '\n';
  text += '═══════════════════════════\n';
  text += '🛍️ Active SKUs: ' + items.length + '\n';
  text += '📦 Total stock units: ' + items.reduce((s, i) => s + (i.stock || 0), 0) + '\n';
  text += '💬 Tracked events: ' + stats.totalEvents + ' (sellers: ' + stats.sellerMessages + ', buyers: ' + stats.buyerMessages + ')\n';
  if (lowStock.length) {
    text += '⚠️ Low stock alert: ' + lowStock.map(i => i.productName + ' (' + i.stock + ' left)').join(', ') + '\n';
  }
  text += '═══════════════════════════\n';
  text += '🤖 Generated by Group Commerce OS (dry-run)';

  return { success: true, groupId, digest: text, lowStockCount: lowStock.length, stats };
}

module.exports = { activityStats, dailyDigest };
