// developerPortal/apiEndpointCatalog.js — curated, redacted catalog of safe existing APIs.
// Preview-only documentation. Does NOT execute or expose destructive/secret behavior.
const ENDPOINTS = [
  { id:'funnel_lead', method:'POST', path:'/api/funnel/lead', module:'Public Funnel', summary:'Capture a public lead (preview)', requestSchema:{name:'string',interest:'string'}, responseSchemaRedacted:{ok:'boolean',leadIdSafe:'string'}, authRequired:false, scopes:['read:public_funnel'], dryRunSafe:true, piiRisk:'medium', notes:'Public-safe' },
  { id:'customer360_preview', method:'GET', path:'/api/customer-360/preview/:idSafe', module:'Customer 360', summary:'Redacted customer profile preview', requestSchema:{}, responseSchemaRedacted:{name:'string',tier:'string',phoneMasked:'string'}, authRequired:true, scopes:['read:customers_preview'], dryRunSafe:true, piiRisk:'high', notes:'Admin-only; redacted' },
  { id:'support_ticket_create', method:'POST', path:'/api/support/tickets', module:'Support Helpdesk', summary:'Create support ticket draft', requestSchema:{subject:'string',priority:'string'}, responseSchemaRedacted:{ticketIdSafe:'string',status:'string'}, authRequired:true, scopes:['write:support_draft'], dryRunSafe:true, piiRisk:'low', notes:'Draft only' },
  { id:'reseller_summary', method:'GET', path:'/api/reseller/summary', module:'Reseller Portal', summary:'Reseller commission summary (preview)', requestSchema:{}, responseSchemaRedacted:{referrals:'number',commissionPreview:'number'}, authRequired:true, scopes:['read:reseller'], dryRunSafe:true, piiRisk:'low', notes:'Preview figures' },
  { id:'templates_list', method:'GET', path:'/api/templates', module:'Template Marketplace', summary:'List installable templates', requestSchema:{}, responseSchemaRedacted:{templates:'array'}, authRequired:true, scopes:['read:templates'], dryRunSafe:true, piiRisk:'none', notes:'' },
  { id:'approvals_list', method:'GET', path:'/api/approvals', module:'Approval Inbox', summary:'List approval items (preview)', requestSchema:{}, responseSchemaRedacted:{items:'array'}, authRequired:true, scopes:['read:approvals'], dryRunSafe:true, piiRisk:'low', notes:'' },
  { id:'audit_events', method:'GET', path:'/api/audit/events', module:'Audit Ledger', summary:'List recent audit events (redacted)', requestSchema:{}, responseSchemaRedacted:{events:'array'}, authRequired:true, scopes:['read:audit'], dryRunSafe:true, piiRisk:'low', notes:'' },
  { id:'kpi_summary', method:'GET', path:'/api/kpi/summary', module:'KPI Summary', summary:'Business KPI summary (preview)', requestSchema:{}, responseSchemaRedacted:{leads:'number',orders:'number',revenuePreview:'number'}, authRequired:true, scopes:['read:kpi'], dryRunSafe:true, piiRisk:'none', notes:'' },
  { id:'compliance_status', method:'GET', path:'/api/compliance/status', module:'Compliance Center', summary:'Compliance status (preview)', requestSchema:{}, responseSchemaRedacted:{status:'string',warnings:'number'}, authRequired:true, scopes:['read:compliance'], dryRunSafe:true, piiRisk:'none', notes:'' },
  { id:'deployment_readiness', method:'GET', path:'/api/deployment/readiness', module:'Deployment', summary:'Deployment readiness (preview)', requestSchema:{}, responseSchemaRedacted:{score:'number',blockers:'array'}, authRequired:true, scopes:['read:deployment'], dryRunSafe:true, piiRisk:'none', notes:'' },
  { id:'billing_preview', method:'GET', path:'/api/billing/preview', module:'SaaS Billing', summary:'Billing preview (no charge)', requestSchema:{}, responseSchemaRedacted:{plan:'string',amountPreview:'number'}, authRequired:true, scopes:['admin:preview'], dryRunSafe:true, piiRisk:'low', notes:'Preview only — never charges' },
];
function list(module){ return module ? ENDPOINTS.filter(e=>e.module===module) : ENDPOINTS; }
function modules(){ return [...new Set(ENDPOINTS.map(e=>e.module))]; }
module.exports = { ENDPOINTS, list, modules };
