// developerPortal/eventSchemas.js — schemas + REDACTED examples for each event (no PII/secrets).
const SCHEMAS = {
  'public_funnel.lead_created':   { schema:{ leadIdSafe:'string', source:'string', interest:'string', createdAt:'iso' }, example:{ leadIdSafe:'ld_***42', source:'whatsapp', interest:'AI Tools', createdAt:'2026-01-01T00:00:00Z' }, piiRisk:'low' },
  'public_funnel.demo_requested': { schema:{ leadIdSafe:'string', slotPreview:'string' }, example:{ leadIdSafe:'ld_***18', slotPreview:'Mon 3-4pm' }, piiRisk:'low' },
  'public_funnel.trial_requested':{ schema:{ leadIdSafe:'string', plan:'string' }, example:{ leadIdSafe:'ld_***07', plan:'starter' }, piiRisk:'low' },
  'support.ticket_created':       { schema:{ ticketIdSafe:'string', subject:'string', priority:'string' }, example:{ ticketIdSafe:'tk_***91', subject:'Login issue', priority:'high' }, piiRisk:'low' },
  'support.ticket_resolved':      { schema:{ ticketIdSafe:'string', resolution:'string' }, example:{ ticketIdSafe:'tk_***91', resolution:'resolved' }, piiRisk:'low' },
  'pilot.onboarding_started':     { schema:{ tenantIdSafe:'string', step:'string' }, example:{ tenantIdSafe:'tn_***33', step:'kickoff' }, piiRisk:'low' },
  'pilot.risk_detected':          { schema:{ tenantIdSafe:'string', risk:'string' }, example:{ tenantIdSafe:'tn_***33', risk:'low_usage' }, piiRisk:'low' },
  'reseller.referral_created':    { schema:{ referralIdSafe:'string' }, example:{ referralIdSafe:'rf_***55' }, piiRisk:'low' },
  'reseller.commission_preview_generated':{ schema:{ referralIdSafe:'string', amountPreview:'number' }, example:{ referralIdSafe:'rf_***55', amountPreview:1500 }, piiRisk:'low' },
  'template.install_preview_created':{ schema:{ templateId:'string' }, example:{ templateId:'tmpl_welcome' }, piiRisk:'none' },
  'approval.item_created':        { schema:{ itemIdSafe:'string', kind:'string' }, example:{ itemIdSafe:'ap_***12', kind:'webhook_delivery' }, piiRisk:'none' },
  'approval.item_approved_preview':{ schema:{ itemIdSafe:'string' }, example:{ itemIdSafe:'ap_***12' }, piiRisk:'none' },
  'audit.event_recorded':         { schema:{ auditIdSafe:'string', action:'string' }, example:{ auditIdSafe:'au_***77', action:'app_created' }, piiRisk:'none' },
  'compliance.warning_created':   { schema:{ warningIdSafe:'string', level:'string' }, example:{ warningIdSafe:'cw_***02', level:'warning' }, piiRisk:'none' },
  'billing.preview_created':      { schema:{ plan:'string', amountPreview:'number' }, example:{ plan:'pro', amountPreview:9900 }, piiRisk:'none' },
  'tenant.setup_preview_created': { schema:{ tenantIdSafe:'string' }, example:{ tenantIdSafe:'tn_***33' }, piiRisk:'none' },
  'customer360.profile_preview_created':{ schema:{ customerIdSafe:'string', tier:'string', phoneMasked:'string' }, example:{ customerIdSafe:'cu_***88', tier:'Gold', phoneMasked:'923****77' }, piiRisk:'high' },
  'growth.campaign_draft_created':{ schema:{ campaignIdSafe:'string', segment:'string' }, example:{ campaignIdSafe:'cm_***19', segment:'vip' }, piiRisk:'none' },
  'channel.post_draft_created':   { schema:{ postIdSafe:'string', channel:'string' }, example:{ postIdSafe:'po_***64', channel:'whatsapp' }, piiRisk:'none' },
  'voice.reply_draft_created':    { schema:{ replyIdSafe:'string' }, example:{ replyIdSafe:'vr_***30' }, piiRisk:'low' },
  'deployment.readiness_checked': { schema:{ score:'number' }, example:{ score:92 }, piiRisk:'none' },
  'incident.created':             { schema:{ incidentIdSafe:'string', severity:'string' }, example:{ incidentIdSafe:'in_***05', severity:'minor' }, piiRisk:'none' },
  'backup.check_completed':       { schema:{ ok:'boolean' }, example:{ ok:true }, piiRisk:'none' },
  'owner.digest_created':         { schema:{ digestIdSafe:'string' }, example:{ digestIdSafe:'dg_***41' }, piiRisk:'none' },
  'generic.system_notice':        { schema:{ message:'string' }, example:{ message:'System notice' }, piiRisk:'none' },
};
module.exports = { SCHEMAS };
