'use strict';
function step(id, journeyId, order, title, page, apiEndpoint, expectedResult, talkingPoints, fallback) { return { id, journeyId, order, title, page:page||null, apiEndpoint:apiEndpoint||null, expectedResult, talkingPoints, safetyNotes:'Preview only; sample/mock data; no live actions.', fallbackIfUnavailable:fallback || 'Show fallback slide/screenshot; module not wired in this build.', status:'pending' }; }
const JOURNEYS = [
 { id:'investor', title:'Founder / Investor 10-minute demo', audience:'investor', durationMinutes:10, steps:[ step('inv1','investor',1,'Landing / pricing preview','/landing.html',null,'Public page loads','Position the SaaS.'), step('inv2','investor',2,'Demo sandbox','/demo-sandbox.html','/api/demo-sandbox/status','Demo mode ON','Safety story.'), step('inv3','investor',3,'Readiness score','/guided-demo.html','/api/guided-demo/readiness','Score ready','Close with metrics.') ] },
 { id:'owner', title:'Small business owner demo', audience:'business_owner', durationMinutes:12, steps:[ step('own1','owner',1,'Business setup','/business-setup.html','/api/business-setup/status','Setup wizard loads','Pick preset.'), step('own2','owner',2,'Support helpdesk','/support-helpdesk.html','/api/support-helpdesk/status','Tickets render','Support workflow.') ] },
 { id:'agency', title:'Agency / reseller demo', audience:'agency', durationMinutes:12, steps:[ step('ag1','agency',1,'Reseller portal','/reseller-portal.html','/api/reseller-portal/status','Portal loads','White-label preview.') ] },
 { id:'developer', title:'Developer / integration demo', audience:'developer', durationMinutes:10, steps:[ step('dev1','developer',1,'Mock events','/demo-sandbox.html',null,'Mock events','No external calls.') ] },
 { id:'qa', title:'Internal QA acceptance demo', audience:'qa', durationMinutes:8, steps:[ step('qa1','qa',1,'Acceptance checklist','/guided-demo.html','/api/guided-demo/checklist','Checklist runs','Sign off.') ] }
].map((j)=>Object.assign({ dryRun:true, liveActionsEnabled:false, status:'ready', goal:j.title, requiredModules:[], sampleDataRequired:true, mockProvidersRequired:true }, j));
module.exports = JOURNEYS;
